name: Build project from mcuexpresso
on:
  push:
    branches-ignore:
    - '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: nxpsemiconductor/mcuxpressoide:11.5.0_5944.x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build Project
        run: |
          cd source/shoh
          mcuxpressoide -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -import . -build all -data .workspace

